// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Try to load DATABASE_URL or DIRECT_URL, but don't fail if not available during build
// The actual connection will be handled by lib/prisma.ts at runtime
const getDatabaseUrl = () => {
  // Try to load from environment
  if (process.env.DIRECT_URL) {
    return process.env.DIRECT_URL;
  }
  if (process.env.DATABASE_URL) {
    return process.env.DATABASE_URL;
  }
  // Fallback for build time (won't be used at runtime)
  // This is a dummy URL that Prisma will accept for schema validation
  return "postgresql://user:password@localhost:5432/dbname";
};

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: getDatabaseUrl(),
  },
});

